### ISSUE TITLE
Export CSV with Title

### ISSUE THREAD

**Issue by elaya** [Rakhmadi/RdataTB#2]
Hi,

The export csv need with heading. Ref enclosed screen shot
![screen](https://user-images.githubusercontent.com/1099403/125163753-4436d200-e1ac-11eb-91e7-e906485016b0.png)
![Uploading screen.png…]()

**Comment by Rakhmadi** [comment]
Hi elaya
Thanks for sharing this issue, issue is fixed now
https://cdn.jsdelivr.net/gh/Rakhmadi/RdataTB@master/dist/index.js

**Comment by elaya** [comment]
Thanks Great!

**Comment by elaya** [comment]
Hi Rakhmadi,

One more 
Data row color differences looks like my screen shot.
![3](https://user-images.githubusercontent.com/1099403/125622952-9795bd52-d7af-44b7-88f8-50b2953e0998.png)
